### ISSUE TITLE
New RA constructions for pagetables

### ISSUE THREAD

**Issue by lzy0505** [logsem/VMSL#5]
### page table in opsem
```
Definition permission : Type :=
  option VMID * bool * gset VMID.

Definition page_table : Type :=
  gmap PID permission.
```

### RA Construction
I propose the following three new constructions:
#### ownership
  `gen_own_preG_inG :> gen_heapGpreS P (option V) Σ;`

Notations:
- `p -@O> i`
- `p -@O> -`

#### exclusiveness
  `gen_excl_preG_inG :> gen_heapGpreS P boolO Σ;`

Notation:
- `p -@E> b`

#### access
 `gen_access_preG_inG :> inG Σ (authR (gmapUR V (dfrac_agreeR (gsetO P))));`

Notations:
- `v -@{q}A [s]`
- `v -@A [s]`

The structures of ownership and exclusiveness are close to the structure of page table in opsem, which implies simple mappings in `state_interp`.
The construction of access was however designed in a quite different manner with the consideration of proving logrel for unknown VMs. 

### TODOs
- [ ] lemmas in `pagetable.v`
- [ ] lemmas in `pageable_extra.v`
- [ ] proof rules for memory sharing
